POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imtvam8iLCJpZCI6IjVkNTYzYjdlZTg2OTc0NjU5NTNjOTAyZiIsImlhdCI6MTU2NTk5NzExNn0.qGf0TnJhsRnzQeWB8XYP2bWruuieZI0lG_fDdYMsAuE

{
  "title": "testing...",
  "author": "ty frimp",
  "url": "local.io",
  "likes": 1
}